# Generated by Django 3.1.1 on 2020-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0002_userprofile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(max_length=70),
        ),
    ]
