# Generated by Django 3.1.1 on 2020-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_auto_20201115_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_university',
            field=models.BooleanField(default=False, verbose_name='大学様用アカウント'),
        ),
    ]
