# Generated by Django 3.1.1 on 2020-11-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0004_userprofile_is_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.category')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.university')),
            ],
        ),
    ]
