# Generated by Django 3.1.1 on 2020-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0005_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='word',
        ),
        migrations.AddField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
